# Generated by Django 2.1.3 on 2020-08-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='index_number',
            field=models.CharField(default='index', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
