# Generated by Django 2.1.3 on 2020-08-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200808_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='search_data',
            field=models.TextField(default='No Search Data'),
        ),
    ]
